# Generated by Django 6.0.5 on 2026-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('yosh', models.IntegerField()),
                ('yonalish', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=150)),
            ],
        ),
    ]
